### ISSUE TITLE
Add service configuration dynamically. 

### ISSUE THREAD

**Issue by willopez** [aerialship/SamlSPBundle#19]
Hi Milos, question and thanks for you consideration in advance. 

I want to add services dynamically, meaning, instead of defining services in a yml file, I want to load the idp metadata, SP's entity_id and base_url from the database when the app in booting. 

I have implemented the EntityDescriptorProviderInterface and I am able to load the XML metadata. 

I am having problems appending an entry to the services cofig option. I want it to look like this after a compiler pass or something like that. How would I accomplish this? thanks

```
....

alpha:
         idp:
               id: custom_entity_descriptor_service
         sp:
            config:
                 entity_id: http://example.com
                 base_url: http://example.com
```
