### ISSUE TITLE
Multiple user providers, please help

### ISSUE THREAD

**Issue by alexadavid** [aerialship/SamlSPBundle#27]
Hello,
I've one problem and I can't find solution now, so I'd like to ask you for a help. I didn't find any other way, how to contact you, so I have to write this issue.

I use three methods for authentication - in_memory, custom user_db and saml_user_provider (custom UserManagerInterface). SamlUser works fine, but I've problem with authentication with other methods. If I go to login_check path, user is authenticated fully (in zend_debug tracking), but after redirecting back to index route, I'm always redirected to saml_login. And symfony tries to log me in with saml_provider.

Can I somehow disable saml login, when user is authenticated in some other method? My security.yml is below. I had to add at least saml/pattern: ^/(?!login_check)... Without it is login_check route redirected too...

Thank you for helping me.

```
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FIT\NetopeerBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            chain:
                providers:          [user_db, in_memory]
        user_db:
            entity: { class: FITNetopeerBundle:User, property: username }
        saml_user_provider:
            id: SamlToState
        in_memory:
            memory:
                users:
                    user:           { password: pass,    roles: [ 'ROLE_USER' ] }
                    adminNoDb:      { password: pass,    roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        saml:
            pattern: ^/(?!login_check)
            anonymous: true
            aerial_ship_saml_sp:
                login_path: /saml/sp/login
                check_path: /saml/sp/acs
                logout_path: /saml/sp/logout
                failure_path: /saml/sp/failure
                metadata_path: /saml/sp/FederationMetadata.xml
                discovery_path: /saml/sp/discovery
                local_logout_path: /logout/
                provider: saml_user_provider
                create_user_if_not_exists: true
                services:
                    openidp:
                        idp:
                            file: "@FITNetopeerBundle/Resources/saml/openidp.metadata.xml"
                        sp:
                            config:
                                # required
                                entity_id: netconfwebgui4
                                # if different then url being used in request
                                # used for construction of assertion consumer and logout urls in SP entity descriptor
                                base_url: https://garnacha.liberouter.org/netconfwebgui/app_dev.php
                            signing:
                                # must implement SPSigningProviderInterface
                                # id: my.signing.provider.service.id

                                # or use built in SPSigningProviderFile with specific certificate and key files
                                cert_file: "@FITNetopeerBundle/Resources/saml/server.pem"
                                key_file: "@FITNetopeerBundle/Resources/saml/server.key"
                                key_pass: ""
                            meta:
                                # must implement SpMetaProviderInterface
                                # id: my.sp.provider.service.id

                                # or use builtin SpMetaConfigProvider
                                # any valid saml name id format or shortcuts: persistent or transient
                                name_id_format: persistent
                                binding:
                                    # any saml binding or shortcuts: post or redirect
                                    authn_request: post
                                    logout_request: post
            logout:
                path: /logout/

        secured_area:
            pattern:    ^
            anonymous:  ~
            form_login:
                check_path: /login_check
                login_path: /login/
            logout:
                path:   /logout/
                target: /

    access_control:
        - { path: ^/login/$, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/saml/sp/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/saml/sp/acs$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(login_check|connections|section|ajax), roles: ROLE_USER}
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
```
