### ISSUE TITLE
Single Logout help

### ISSUE THREAD

**Issue by tamlyn** [aerialship/SamlSPBundle#29]
I'm trying to get Single Logout working but I'm confused about what is meant to be happening.

Assuming my Symfony app is on `app.com` and the IdP is on `sso.net`:
1. I type `app.com` into my browser
2. I am redirected to `app.com/saml/sp/login`
3. which redirects to `sso.net/adfs/ls/?SAMLRequest=...`
4. I enter my credentials and am directed to (via a silent POST) to `app.net/saml/sp/acs`
5. which redirects to `app.com/` and I am logged in.

This is all as expected. However when I want to log out of my app:
1. I click my app logout link which goes to `app.com/saml/sp/logout` 
2. which redirects to `app.com/logout` 
3. which redirects to `app.com/`
4. which redirects to `app.com/saml/sp/login`
5. which redirects to `sso.net/adfs/ls/?SAMLRequest=...`
6. which redirects (via a silent POST) to `app.net/saml/sp/acs`
7. which redirects to `app.com/` and I am logged in again!

Shouldn't I be getting redirected to the SSO server with a LogoutRequest at some point? 

Here's my firewall config:

```
firewalls:
    saml:
        pattern: ^/
        anonymous: ~
        aerial_ship_saml_sp:
            provider: saml_provider
            services:
                adfs:
                    idp:
                        file: "@SiteBundle/Resources/saml/idp-metadata.xml"
                    sp:
                        config:
                            entity_id: https://[...]
                            base_url: https://[...]
                        signing:
                            cert_file: "@SiteBundle/Resources/saml/public.pem"
                            key_file: "@SiteBundle/Resources/saml/private.pem"
                            key_pass: ""
```

Has anyone got single signout working with this bundle? Do I have a configuration problem?
