### ISSUE TITLE
NameID question

### ISSUE THREAD

**Issue by safar** [aerialship/SamlSPBundle#42]
I get errors like this after successful authentication:

```
Username "_ebaa3a311a590637ceac45648057acdf3b5e52a399" does not exist.
```

This string changes with every authentication so it's not possible to authenticate since I cannot guess in the future how this string will look like.

Is this a normal behaviour? Can I set somehow to use different attribute of SAML response as NameID?

This is the part of security.yml

```
providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
                    _5gfd5gfdgdfg0637ceac456480a7bhdf3b5e52h097: { roles: [ 'ROLE_USER' ]}
        #saml_user_provider:
            #id: my.custom.service # implements UserManagerInterface
    firewalls:   
      saml:
            pattern: ^/
            anonymous: true
            aerial_ship_saml_sp:
                create_user_if_not_exists: false
                local_logout_path: /logout
                provider: in_memory               
```

Also are there more detailed instructions on how to implement UserManagerInterface? Maybe with an example. I'm a beginner with Symfony so the current ones are quite vague.
