### ISSUE TITLE
SP Configuration with ADFS

### ISSUE THREAD

**Issue by fayez-minside** [aerialship/SamlSPBundle#59]
Hello,

I am trying to make a SSO connection via a remote ADFS.

The ADFS admin gave me the federation-metada.xml and certificate .cer file which I converted to a .pem file because it is said that SimpleSAML was tested with pem.

I am using SSL in my domain.

I understand that I must put the ADFS federation metada in the IDP config.
But what can I put in the signing part of my SP config?
Is it the ADFS public certificate or mine?
Also is it good enough or I must add my domain key file (private) and passphrase?

This is what my config looks like with the ADFS public key and my domain private key:
Is it correct?

``` yaml
security:
    providers:
        de_sso_provider:
            id: de_sso.user_provider

    firewalls:
        de_sso_firewall:
            pattern: ^/
            anonymous: true
            aerial_ship_saml_sp:
                local_logout_path: /logout
                provider: de_sso_provider
                services:
                    de_services:
                        idp:
                            file: "@MDeSSOBundle/Resources/adfs-FederationMetadata.xml"
                        sp:
                            config:
                                entity_id: %de_sp_entity_id%
                            signing:
                                # use built in SPSigningProviderFile with specific certificate and key files
                                cert_file: "@MDeSSOBundle/Resources/adfs-saml-public-certificate.pem"
                                key_file: "@MDeSSOBundle/Resources/my-domain-private-key-file.key"
                                key_pass: ""
                            meta:
                                # use builtin SpMetaConfigProvider
                                # any valid saml name id format or shortcuts: persistent or transient
                                name_id_format: persistent
                                binding:
                                    # any saml binding or shortcuts: post or redirect
                                    authn_request: redirect
                                    response: post
                                    logout_request: redirect
            logout:
                path: /logout
            context: insideboard_firewall_context

    access_control:
        - { path: ^/saml/sp/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/saml/sp/acs, roles: IS_AUTHENTICATED_ANONYMOUSLY }
```

@tmilos Any ideas on how sp.signing and sp.meta.binding should be configured?

Thanks
