### ISSUE TITLE
Question - redirect to target resource and don't know what user is logged in.

### ISSUE THREAD

**Issue by BernardoSilva** [aerialship/SamlSPBundle#84]
Hi,

I am having some issues in my SSO implementation.

I have just pasted a link on IDP to my SP `/saml/sp/login`.
1. User click and is redirected to my SP `/saml/sp/login` page.
2. It detects only one IDP service so it redirect to `/saml/sp/login?as=my_service`
3. I creates a SAML Assert Request to IDP.
4. Assuming user is logged in IDP posts the SAML assertion signed to `/saml/sp/acs` page
5. I created my own Service Implementing `UserManagerInterface`, I receive the IDP assertion with all attributes and I return the user found.
6. Then I am redirected to my SP `entity_id` 

At this point I don't have any information about the user I am trying to authenticate.
Should I implement my own `/saml/sp/acs` where I can redirect to `myaap.com?token=myuniquetokentologinuser` ?

Or I am missing something?

my config is similar to this:
```yml
provider: saml_user_provider
        create_user_if_not_exists: true
        services:
            saml_authentication:
                idp:
                    file: "@VendornameBundle/Resources/idp-FederationMetadata.xml"
                sp:
                    config:
                        entity_id: "http://api.%base_host%/"
```

Sorry if my question is obvious but I am stuck with this because of this last bit.

I just need to know how to get the user I just loaded before being redirected to my API again, because I need to redirect the user to a different URL where my front end app is e.g  `http://%base_host%/`.

**Comment by tmilos** [comment]
You should have the user you retured from user manager in you security context token, if under same firewall as the sp security listener

**Comment by BernardoSilva** [comment]
@tmilos I own you a  :beer: !
After 2 days struggling with this it was just because I had 2 firewalls.

Just by adding this, I was able to get the logged in user. 
```yml
firewalls:
        saml:
            context: primary_auth
        api_area:
            context: primary_auth
```

If you come to London I would like to get you :beer:  ! hehe

Are you planing on building a bundle for IDP? 
I would like to help develop and maintain that.
Would be awesome for testing purposes as well.
