### ISSUE TITLE
The service "security.firewall.map.context.saml" has a dependency on a non-existent service "session".

### ISSUE THREAD

**Issue by tkuldeep** [aerialship/SamlSPBundle#96]
Hi,
I want to use it this bundle for redirecting `symfony application as a SP` to IDP.
* I am using symfony version 2.6.6. and mongo DB.

When I installed this bundle via composer and configured my bundle as described in https://github.com/aerialship/SamlSPBundle/blob/master/src/AerialShip/SamlSPBundle/Resources/doc/index.md.

Now when I tried to start server by command `php app/console server:run`, it is throwing an exception.
```
[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]                              
  The service "security.firewall.map.context.saml" has a dependency on a non-existent service "session". 
```

So I walked through code of this bundle, then I think file **services.yml** contains service
```
aerial_ship_saml_sp.state.store.request:
        class: %aerial_ship_saml_sp.state.store.request.class%
        arguments: [@session, ~]
        public: false
        abstract: true
 ```

Here **@session** service does not exist.  So now what should I do. Please assist here.
