### ISSUE TITLE
"Assertion must be signed" failure

### ISSUE THREAD

**Issue by quentint** [aerialship/SamlSPBundle#97]
Hi,
I've set up a `aerial_ship_saml_sp` firewall service like this:

```
                    rm:
                        idp:
                            file: "@idp-metadata.xml"
                            entity_id: [URL]
                        sp:
                            config:
                                entity_id: [URL]
```

I didn't specify the `want_assertions_signed` option so it falls back to `false` (by the way, explicitely setting it to `false` throws an error, because of the `->cannotBeEmpty()` call in `SamlSpFactory.php` which can be removed).

The generated `FederationMetadata.xml` contains the correct `WantAssertionsSigned="false"` attribute, but every authentication attempt through this service fails with a `Assertion must be signed` failure.

How come this errors comes up? Is there something to do to prevent that?
Any tips or links that could help me?

Thanks in advance!
